version: "3.8"

services:
  app:
    image: pedrowww777/app:dev
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      LOG_LEVEL: warn
      DEBUG: "false"
    depends_on:
      - db

  frontend:
    image: pedrowww777/frontend:dev
    ports:
      - "8080:80"

  db:
    image: pedrowww777/mysql:dev
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
    ports:
      - "3306:3306"
    volumes:
      - dev-db-data:/var/lib/mysql

volumes:
  dev-db-data:

