version: "3.8"

services:
  app:
    image: pedrowww777/app:prod
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      LOG_LEVEL: debug
      DEBUG: "true"
    depends_on:
      - db

  frontend:
    image: pedrowww777/frontend:prod
    ports:
      - "8080:80"

  db:
    image: pedrowww777/mysql:prod
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todos
    ports:
      - "3306:3306"
    volumes:
      - prod-db-data:/var/lib/mysql

volumes:
  prod-db-data:
